name: Create Release
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@4c5670f886fe259db4d11222f7dff41c1382304d # ratchet:google-github-actions/release-please-action@v3.7.12
        with:
          release-type: python
          token: ${{ secrets.SPDXMERGE_GITHUB_TOKEN }}
