name: Create Release
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # ratchet:google-github-actions/release-please-action@v3.7.11
        with:
          release-type: python
          token: ${{ secrets.SPDXMERGE_GITHUB_TOKEN }}
