name: Create Release
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # ratchet:google-github-actions/release-please-action@v3.7.13
        with:
          release-type: python
          token: ${{ secrets.SPDXMERGE_GITHUB_TOKEN }}
