name: Create Release
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29 # ratchet:google-github-actions/release-please-action@v3.7.10
        with:
          release-type: python
          token: ${{ secrets.SPDXMERGE_GITHUB_TOKEN }}
